version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: nanoid
    versions:
    - "^3.0.0"
  - dependency-name: puppeteer-core
    versions:
    - 8.0.0
