extends: google
env:
  browser: true
  serviceworker: true
  worker: true
globals:
  Logging: true
parserOptions:
  sourceType: module
rules:
  comma-dangle:
    - error
    - arrays: never
      objects: never
      imports: never
      exports: never
      functions: never
  max-nested-callbacks: 0
  no-warning-comments: 0
  require-jsdoc: 0
  max-len: 0
  object-curly-spacing: 0
  one-var: 0
  arrow-parens: 0
  new-cap: 0
  camelcase: 0
  no-var: 2
  prefer-const: 2
  no-confusing-arrow: 2
  prefer-arrow-callback: 2
  consistent-this:
    - error
    - window.AuthenticationContext
