parser: '@typescript-eslint/parser'
extends:
  - plugin:@typescript-eslint/recommended
  - plugin:compat/recommended
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/indent': [error, 2]
  '@typescript-eslint/interface-name-prefix': off
  '@typescript-eslint/no-namespace':
    - error
    - allowDeclarations: true
  '@typescript-eslint/camelcase':
    - always
    - ignoreDestructuring: true
  '@typescript-eslint/no-var-requires': off
  '@typescript-eslint/no-explicit-any': off
overrides:
  - files:
    - karma.*
    - rollup.*
    rules:
      'compat/compat': off
settings:
  polyfills:
    - Promise
    - fetch
    - URL
    - Request

