sudo: false
language: node_js
node_js: stable
cache:
  yarn: true
  directories:
    - node_modules
# TODO: Remove this before merging!
# branches:
#   only:
#     - master
#     - /^greenkeeper/.*$/
script:
  - yarn start lint
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then yarn start test.sauce; fi
  - yarn start test
  - yarn start docs
after_success:
  - yarn start report-coverage
  - yarn start semantic-release
deploy:
  provider: pages
  skip_cleanup: true
  email: bot@salte.io
  name: Salte Bot
  github_token: $GH_TOKEN
  local_dir: docs
  on:
    branch: master
notifications:
  email: change
