sudo: false
language: node_js
node_js:
- 6.3
cache:
  directories:
  - node_modules
branches:
  only:
    - master
notifications:
  email: false
before_script:
  - npm prune
script:
  - npm run test
  - npm run build
after_success:
# TODO: Add coverage support
#   - npm run report-coverage
  - npm run semantic-release
