sudo: false
language: node_js
node_js: lts/*
cache: npm
branches:
  only:
    - master
script:
  - npm start lint
  - npm start check-types
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ]; then npm start test.ci; fi
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ]; then npm start test.smoke; fi
  - npm start test
after_success:
  - npm start report-coverage
  - npm start semantic-release
addons:
  sauce_connect: true
  chrome: stable
deploy:
  provider: pages
  skip_cleanup: true
  email: bot@salte.io
  name: Salte Bot
  github_token: $GH_TOKEN
  local_dir: generated-docs
  on:
    branch: master
notifications:
  email: change
