sudo: false
language: node_js
node_js: stable
cache:
  yarn: true
  directories:
    - node_modules
branches:
  only:
    - master
    - 2.0-preview
    - /^greenkeeper-.*$/
before_install:
  - yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script:
  - yarn run lint
  - yarn run test:sauce
  - yarn run test
  - yarn run docs
after_script: greenkeeper-lockfile-upload
after_success:
  - yarn run report-coverage
  - yarn run semantic-release
deploy:
  provider: pages
  skip_cleanup: true
  email: bot@salte.io
  name: Salte Bot
  github_token: $GH_TOKEN
  local_dir: docs
  on:
    branch: 2.0-preview
notifications:
  email: change
addons:
  jwt:
    secure: VL4NEo40OGQX6tEDr8qjNPIDNHuXafWucHCgSTTcIGBdGcdzf9g+EZULhGkcyz9UypMbEvxP6JAlBZHVE04/vG1I8kQ4o3ayG2v09Tl2zzTeRpJNAVwlufUyz+zWG5+S3/NWzCAG9LYOQucbDX1DZgUhgyfAGNJavTgIK2BNAiumb3pSsh1Cw0paSf7uWYCtDTB/KKJedkyMwjftmtBkbLNKa0SD2mBlKb/ZJYro7CC0g3BKD+9tmHrOsX1wiSFxSxUHPBHccfab9SGduXfe1pXenNrJ+H8EtddqnIRz9CaT3mMSSJwtV3PIycQ8DemkqPUOiO4X2Q+bx2uaLHlESK+XOeWI1AO43YEUF0qDGnmXHkpyvIJr0v9w5bjz4U4T2f0hcQDx5tdMPCLc1LcfmtS+g+oO9fHbjPHjkNlnhOOezt+wgLFN/QXcpMo6SuJJHM1y/0KQ6kgaVUAiDatMVtlPbL/fvje92MqmbMpgCrAr9Wx+T4uMhfCzFnpDz8sXtbL1gnDcOf7fzRS05lLi6EfSg/9+oteQn+6DauShN7rDiiq7zY/Dwe55dZNYAJqWUw1yyt42Bt/aMQtiKkifosCJc/JhMPX8T22dAUhO8hCRvc2EMXa+5sE0boQJE+KBebIguJfSWwWl0Cay9YNY5H0AqWfuHsvGq1OgG1U2xzg=
