sudo: false
language: node_js
node_js: lts/*
cache: npm
branches:
  only:
    - master
    - /^ci/.*$/
script:
  - npm start lint
  - npm start check-types
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then npm start test.ci; fi
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then npm start test.smoke; fi
  - npm start test
  - npm start build.docs
after_success:
  - npm start report-coverage
  - npm start semantic-release
addons:
  sauce_connect: true
  chrome: stable
deploy:
  provider: pages
  skip_cleanup: true
  email: bot@salte.io
  name: Salte Bot
  github_token: $GH_TOKEN
  repo: salte-auth/salte-auth.github.io
  target_branch: master
  local_dir: generated-docs
  on:
    branch: master
notifications:
  email: change
