name: salte-io/salte-auth
ui: mocha-bdd
scripts:
  - /node_modules/sinon/pkg/sinon.js
browsers:
  - name: chrome
    version: latest
    platform: Windows 10
  - name: firefox
    version: latest
    platform: Windows 10
  - name: microsoftedge
    version: latest
  - name: internet explorer
    version: 11
    platform: Windows 8.1
  - name: internet explorer
    version: 10
    platform: Windows 7
  - name: safari
    version: 7..9
builder: zuul-builder-webpack
webpack: ./webpack.test.config
