window.esdocSearchIndex = [
  [
    "@salte-auth/salte-auth/dist/salte-auth.providers.js~providers",
    "class/src/salte-auth.providers.js~Providers.html",
    "<span>Providers</span> <span class=\"search-result-import-path\">@salte-auth/salte-auth/dist/salte-auth.providers.js</span>",
    "class"
  ],
  [
    "@salte-auth/salte-auth~salteauth",
    "class/src/salte-auth.js~SalteAuth.html",
    "<span>SalteAuth</span> <span class=\"search-result-import-path\">@salte-auth/salte-auth</span>",
    "class"
  ],
  [
    "@salte-auth/salte-auth/dist/providers/auth0.js~salteauthauth0provider",
    "class/src/providers/auth0.js~SalteAuthAuth0Provider.html",
    "<span>SalteAuthAuth0Provider</span> <span class=\"search-result-import-path\">@salte-auth/salte-auth/dist/providers/auth0.js</span>",
    "class"
  ],
  [
    "@salte-auth/salte-auth/dist/providers/azure.js~salteauthazureprovider",
    "class/src/providers/azure.js~SalteAuthAzureProvider.html",
    "<span>SalteAuthAzureProvider</span> <span class=\"search-result-import-path\">@salte-auth/salte-auth/dist/providers/azure.js</span>",
    "class"
  ],
  [
    "@salte-auth/salte-auth/dist/providers/cognito.js~salteauthcognitoprovider",
    "class/src/providers/cognito.js~SalteAuthCognitoProvider.html",
    "<span>SalteAuthCognitoProvider</span> <span class=\"search-result-import-path\">@salte-auth/salte-auth/dist/providers/cognito.js</span>",
    "class"
  ],
  [
    "@salte-auth/salte-auth/dist/salte-auth.mixin.js~salteauthmixingenerator",
    "function/index.html#static-function-SalteAuthMixinGenerator",
    "<span>SalteAuthMixinGenerator</span> <span class=\"search-result-import-path\">@salte-auth/salte-auth/dist/salte-auth.mixin.js</span>",
    "function"
  ],
  [
    "@salte-auth/salte-auth/dist/providers/okta.js~salteauthoktaprovider",
    "class/src/providers/okta.js~SalteAuthOktaProvider.html",
    "<span>SalteAuthOktaProvider</span> <span class=\"search-result-import-path\">@salte-auth/salte-auth/dist/providers/okta.js</span>",
    "class"
  ],
  [
    "@salte-auth/salte-auth/dist/salte-auth.profile.js~salteauthprofile",
    "class/src/salte-auth.profile.js~SalteAuthProfile.html",
    "<span>SalteAuthProfile</span> <span class=\"search-result-import-path\">@salte-auth/salte-auth/dist/salte-auth.profile.js</span>",
    "class"
  ],
  [
    "@salte-auth/salte-auth/dist/salte-auth.utilities.js~salteauthutilities",
    "class/src/salte-auth.utilities.js~SalteAuthUtilities.html",
    "<span>SalteAuthUtilities</span> <span class=\"search-result-import-path\">@salte-auth/salte-auth/dist/salte-auth.utilities.js</span>",
    "class"
  ],
  [
    "@salte-auth/salte-auth/dist/providers/wso2.js~salteauthwso2provider",
    "class/src/providers/wso2.js~SalteAuthWSO2Provider.html",
    "<span>SalteAuthWSO2Provider</span> <span class=\"search-result-import-path\">@salte-auth/salte-auth/dist/providers/wso2.js</span>",
    "class"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/providers/auth0.js",
    "file/src/providers/auth0.js.html",
    "src/providers/auth0.js",
    "file"
  ],
  [
    "src/providers/auth0.js~salteauthauth0provider.deauthorizeurl",
    "class/src/providers/auth0.js~SalteAuthAuth0Provider.html#static-method-deauthorizeUrl",
    "src/providers/auth0.js~SalteAuthAuth0Provider.deauthorizeUrl",
    "method"
  ],
  [
    "src/providers/azure.js",
    "file/src/providers/azure.js.html",
    "src/providers/azure.js",
    "file"
  ],
  [
    "src/providers/azure.js~salteauthazureprovider.authorizeendpoint",
    "class/src/providers/azure.js~SalteAuthAzureProvider.html#static-method-authorizeEndpoint",
    "src/providers/azure.js~SalteAuthAzureProvider.authorizeEndpoint",
    "method"
  ],
  [
    "src/providers/azure.js~salteauthazureprovider.deauthorizeurl",
    "class/src/providers/azure.js~SalteAuthAzureProvider.html#static-method-deauthorizeUrl",
    "src/providers/azure.js~SalteAuthAzureProvider.deauthorizeUrl",
    "method"
  ],
  [
    "src/providers/cognito.js",
    "file/src/providers/cognito.js.html",
    "src/providers/cognito.js",
    "file"
  ],
  [
    "src/providers/cognito.js~salteauthcognitoprovider.authorizeendpoint",
    "class/src/providers/cognito.js~SalteAuthCognitoProvider.html#static-method-authorizeEndpoint",
    "src/providers/cognito.js~SalteAuthCognitoProvider.authorizeEndpoint",
    "method"
  ],
  [
    "src/providers/cognito.js~salteauthcognitoprovider.deauthorizeurl",
    "class/src/providers/cognito.js~SalteAuthCognitoProvider.html#static-method-deauthorizeUrl",
    "src/providers/cognito.js~SalteAuthCognitoProvider.deauthorizeUrl",
    "method"
  ],
  [
    "src/providers/cognito.js~salteauthcognitoprovider.defaultconfig",
    "class/src/providers/cognito.js~SalteAuthCognitoProvider.html#static-member-defaultConfig",
    "src/providers/cognito.js~SalteAuthCognitoProvider.defaultConfig",
    "member"
  ],
  [
    "src/providers/okta.js",
    "file/src/providers/okta.js.html",
    "src/providers/okta.js",
    "file"
  ],
  [
    "src/providers/okta.js~salteauthoktaprovider.authorizeendpoint",
    "class/src/providers/okta.js~SalteAuthOktaProvider.html#static-method-authorizeEndpoint",
    "src/providers/okta.js~SalteAuthOktaProvider.authorizeEndpoint",
    "method"
  ],
  [
    "src/providers/okta.js~salteauthoktaprovider.deauthorizeurl",
    "class/src/providers/okta.js~SalteAuthOktaProvider.html#static-method-deauthorizeUrl",
    "src/providers/okta.js~SalteAuthOktaProvider.deauthorizeUrl",
    "method"
  ],
  [
    "src/providers/wso2.js",
    "file/src/providers/wso2.js.html",
    "src/providers/wso2.js",
    "file"
  ],
  [
    "src/providers/wso2.js~salteauthwso2provider.deauthorizeurl",
    "class/src/providers/wso2.js~SalteAuthWSO2Provider.html#static-method-deauthorizeUrl",
    "src/providers/wso2.js~SalteAuthWSO2Provider.deauthorizeUrl",
    "method"
  ],
  [
    "src/salte-auth.js",
    "file/src/salte-auth.js.html",
    "src/salte-auth.js",
    "file"
  ],
  [
    "src/salte-auth.js~config",
    "typedef/index.html#static-typedef-Config",
    "src/salte-auth.js~Config",
    "typedef"
  ],
  [
    "src/salte-auth.js~loginconfig",
    "typedef/index.html#static-typedef-LoginConfig",
    "src/salte-auth.js~LoginConfig",
    "typedef"
  ],
  [
    "src/salte-auth.js~redirecturls",
    "typedef/index.html#static-typedef-RedirectURLs",
    "src/salte-auth.js~RedirectURLs",
    "typedef"
  ],
  [
    "src/salte-auth.js~salteauth#$$refreshtoken",
    "class/src/salte-auth.js~SalteAuth.html#instance-method-$$refreshToken",
    "src/salte-auth.js~SalteAuth#$$refreshToken",
    "method"
  ],
  [
    "src/salte-auth.js~salteauth#constructor",
    "class/src/salte-auth.js~SalteAuth.html#instance-constructor-constructor",
    "src/salte-auth.js~SalteAuth#constructor",
    "method"
  ],
  [
    "src/salte-auth.js~salteauth#loginwithiframe",
    "class/src/salte-auth.js~SalteAuth.html#instance-method-loginWithIframe",
    "src/salte-auth.js~SalteAuth#loginWithIframe",
    "method"
  ],
  [
    "src/salte-auth.js~salteauth#loginwithnewtab",
    "class/src/salte-auth.js~SalteAuth.html#instance-method-loginWithNewTab",
    "src/salte-auth.js~SalteAuth#loginWithNewTab",
    "method"
  ],
  [
    "src/salte-auth.js~salteauth#loginwithpopup",
    "class/src/salte-auth.js~SalteAuth.html#instance-method-loginWithPopup",
    "src/salte-auth.js~SalteAuth#loginWithPopup",
    "method"
  ],
  [
    "src/salte-auth.js~salteauth#loginwithredirect",
    "class/src/salte-auth.js~SalteAuth.html#instance-method-loginWithRedirect",
    "src/salte-auth.js~SalteAuth#loginWithRedirect",
    "method"
  ],
  [
    "src/salte-auth.js~salteauth#logoutwithiframe",
    "class/src/salte-auth.js~SalteAuth.html#instance-method-logoutWithIframe",
    "src/salte-auth.js~SalteAuth#logoutWithIframe",
    "method"
  ],
  [
    "src/salte-auth.js~salteauth#logoutwithnewtab",
    "class/src/salte-auth.js~SalteAuth.html#instance-method-logoutWithNewTab",
    "src/salte-auth.js~SalteAuth#logoutWithNewTab",
    "method"
  ],
  [
    "src/salte-auth.js~salteauth#logoutwithpopup",
    "class/src/salte-auth.js~SalteAuth.html#instance-method-logoutWithPopup",
    "src/salte-auth.js~SalteAuth#logoutWithPopup",
    "method"
  ],
  [
    "src/salte-auth.js~salteauth#logoutwithredirect",
    "class/src/salte-auth.js~SalteAuth.html#instance-method-logoutWithRedirect",
    "src/salte-auth.js~SalteAuth#logoutWithRedirect",
    "method"
  ],
  [
    "src/salte-auth.js~salteauth#mixin",
    "class/src/salte-auth.js~SalteAuth.html#instance-member-mixin",
    "src/salte-auth.js~SalteAuth#mixin",
    "member"
  ],
  [
    "src/salte-auth.js~salteauth#off",
    "class/src/salte-auth.js~SalteAuth.html#instance-method-off",
    "src/salte-auth.js~SalteAuth#off",
    "method"
  ],
  [
    "src/salte-auth.js~salteauth#on",
    "class/src/salte-auth.js~SalteAuth.html#instance-method-on",
    "src/salte-auth.js~SalteAuth#on",
    "method"
  ],
  [
    "src/salte-auth.js~salteauth#profile",
    "class/src/salte-auth.js~SalteAuth.html#instance-member-profile",
    "src/salte-auth.js~SalteAuth#profile",
    "member"
  ],
  [
    "src/salte-auth.js~salteauth#refreshtoken",
    "class/src/salte-auth.js~SalteAuth.html#instance-method-refreshToken",
    "src/salte-auth.js~SalteAuth#refreshToken",
    "method"
  ],
  [
    "src/salte-auth.js~salteauth#retrieveaccesstoken",
    "class/src/salte-auth.js~SalteAuth.html#instance-method-retrieveAccessToken",
    "src/salte-auth.js~SalteAuth#retrieveAccessToken",
    "method"
  ],
  [
    "src/salte-auth.js~validation",
    "typedef/index.html#static-typedef-Validation",
    "src/salte-auth.js~Validation",
    "typedef"
  ],
  [
    "src/salte-auth.mixin.js",
    "file/src/salte-auth.mixin.js.html",
    "src/salte-auth.mixin.js",
    "file"
  ],
  [
    "src/salte-auth.profile.js",
    "file/src/salte-auth.profile.js.html",
    "src/salte-auth.profile.js",
    "file"
  ],
  [
    "src/salte-auth.profile.js~salteauthprofile#$parseparams",
    "class/src/salte-auth.profile.js~SalteAuthProfile.html#instance-method-$parseParams",
    "src/salte-auth.profile.js~SalteAuthProfile#$parseParams",
    "method"
  ],
  [
    "src/salte-auth.profile.js~salteauthprofile#accesstokenexpired",
    "class/src/salte-auth.profile.js~SalteAuthProfile.html#instance-member-accessTokenExpired",
    "src/salte-auth.profile.js~SalteAuthProfile#accessTokenExpired",
    "member"
  ],
  [
    "src/salte-auth.profile.js~salteauthprofile#constructor",
    "class/src/salte-auth.profile.js~SalteAuthProfile.html#instance-constructor-constructor",
    "src/salte-auth.profile.js~SalteAuthProfile#constructor",
    "method"
  ],
  [
    "src/salte-auth.profile.js~salteauthprofile#idtokenexpired",
    "class/src/salte-auth.profile.js~SalteAuthProfile.html#instance-member-idTokenExpired",
    "src/salte-auth.profile.js~SalteAuthProfile#idTokenExpired",
    "member"
  ],
  [
    "src/salte-auth.profile.js~salteauthprofile#userinfo",
    "class/src/salte-auth.profile.js~SalteAuthProfile.html#instance-member-userInfo",
    "src/salte-auth.profile.js~SalteAuthProfile#userInfo",
    "member"
  ],
  [
    "src/salte-auth.providers.js",
    "file/src/salte-auth.providers.js.html",
    "src/salte-auth.providers.js",
    "file"
  ],
  [
    "src/salte-auth.providers.js~providers.auth0",
    "class/src/salte-auth.providers.js~Providers.html#static-member-auth0",
    "src/salte-auth.providers.js~Providers.auth0",
    "member"
  ],
  [
    "src/salte-auth.providers.js~providers.azure",
    "class/src/salte-auth.providers.js~Providers.html#static-member-azure",
    "src/salte-auth.providers.js~Providers.azure",
    "member"
  ],
  [
    "src/salte-auth.providers.js~providers.cognito",
    "class/src/salte-auth.providers.js~Providers.html#static-member-cognito",
    "src/salte-auth.providers.js~Providers.cognito",
    "member"
  ],
  [
    "src/salte-auth.providers.js~providers.okta",
    "class/src/salte-auth.providers.js~Providers.html#static-member-okta",
    "src/salte-auth.providers.js~Providers.okta",
    "member"
  ],
  [
    "src/salte-auth.providers.js~providers.wso2",
    "class/src/salte-auth.providers.js~Providers.html#static-member-wso2",
    "src/salte-auth.providers.js~Providers.wso2",
    "member"
  ],
  [
    "src/salte-auth.utilities.js",
    "file/src/salte-auth.utilities.js.html",
    "src/salte-auth.utilities.js",
    "file"
  ],
  [
    "src/salte-auth.utilities.js~salteauthutilities#addfetchinterceptor",
    "class/src/salte-auth.utilities.js~SalteAuthUtilities.html#instance-method-addFetchInterceptor",
    "src/salte-auth.utilities.js~SalteAuthUtilities#addFetchInterceptor",
    "method"
  ],
  [
    "src/salte-auth.utilities.js~salteauthutilities#addxhrinterceptor",
    "class/src/salte-auth.utilities.js~SalteAuthUtilities.html#instance-method-addXHRInterceptor",
    "src/salte-auth.utilities.js~SalteAuthUtilities#addXHRInterceptor",
    "method"
  ],
  [
    "src/salte-auth.utilities.js~salteauthutilities#checkformatchingurl",
    "class/src/salte-auth.utilities.js~SalteAuthUtilities.html#instance-method-checkForMatchingUrl",
    "src/salte-auth.utilities.js~SalteAuthUtilities#checkForMatchingUrl",
    "method"
  ],
  [
    "src/salte-auth.utilities.js~salteauthutilities#constructor",
    "class/src/salte-auth.utilities.js~SalteAuthUtilities.html#instance-constructor-constructor",
    "src/salte-auth.utilities.js~SalteAuthUtilities#constructor",
    "method"
  ],
  [
    "src/salte-auth.utilities.js~salteauthutilities#createiframe",
    "class/src/salte-auth.utilities.js~SalteAuthUtilities.html#instance-method-createIframe",
    "src/salte-auth.utilities.js~SalteAuthUtilities#createIframe",
    "method"
  ],
  [
    "src/salte-auth.utilities.js~salteauthutilities#createurl",
    "class/src/salte-auth.utilities.js~SalteAuthUtilities.html#instance-method-createUrl",
    "src/salte-auth.utilities.js~SalteAuthUtilities#createUrl",
    "method"
  ],
  [
    "src/salte-auth.utilities.js~salteauthutilities#isroutesecure",
    "class/src/salte-auth.utilities.js~SalteAuthUtilities.html#instance-method-isRouteSecure",
    "src/salte-auth.utilities.js~SalteAuthUtilities#isRouteSecure",
    "method"
  ],
  [
    "src/salte-auth.utilities.js~salteauthutilities#opennewtab",
    "class/src/salte-auth.utilities.js~SalteAuthUtilities.html#instance-method-openNewTab",
    "src/salte-auth.utilities.js~SalteAuthUtilities#openNewTab",
    "method"
  ],
  [
    "src/salte-auth.utilities.js~salteauthutilities#openpopup",
    "class/src/salte-auth.utilities.js~SalteAuthUtilities.html#instance-method-openPopup",
    "src/salte-auth.utilities.js~SalteAuthUtilities#openPopup",
    "method"
  ],
  [
    "src/salte-auth.utilities.js~salteauthutilities#resolveurl",
    "class/src/salte-auth.utilities.js~SalteAuthUtilities.html#instance-method-resolveUrl",
    "src/salte-auth.utilities.js~SalteAuthUtilities#resolveUrl",
    "method"
  ]
]